name = "jurnalvisualkevin"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-04-03"

pages_build_output_dir = "./.vercel/output/static"

[vars]
API_KEY = "1234567asdf"
YARN_VERSION = "1"